# Generated by Django 5.2.11 on 2026-02-06 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chewy_attachment_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='storage_config_id',
            field=models.CharField(blank=True, db_index=True, help_text='S3存储配置的唯一标识，为空表示使用本地存储或系统默认配置', max_length=100, null=True, verbose_name='存储配置ID'),
        ),
    ]
